name: ci
on: [push, pull_request]

jobs:
  build_and_deploy:
    env:
        # latest non-preview version(+1) at the time of writing this CI script
        # NOTE!!: sync with version number in Xamarin.Forms.Platform.GTK.csproj
        BASE_VERSION: 5.0.0.2515
        DEFAULT_REF_TO_NUGET_PUSH: refs/heads/5.0.0
        CONFIGURATION: Release

    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Download Nuget.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 5.4.0
        
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore
      run: msbuild /restore Xamarin.Forms.sln

    - name: Build
      run: msbuild .\Xamarin.Forms.sln -p:Configuration=${{env.CONFIGURATION}}

    - name: Package and Upload
      run: |
        git clone https://github.com/nblockchain/fsx
        $version = `.\fsx\Tools\fsi.bat fsx\Tools\nugetPush.fsx --output-version $env:BASE_VERSION`

        nuget pack .nuspec/Xamarin.Forms.nuspec -p "version=$version;Configuration=$env:CONFIGURATION"
        nuget pack .nuspec/Xamarin.Forms.Platform.GTK.nuspec -p "version=$version;Configuration=$env:CONFIGURATION;core_version=$version"

        If ($Env:GITHUB_REF -eq $Env:DEFAULT_REF_TO_NUGET_PUSH) {
            If ('${{ secrets.NUGET_API_KEY }}' -ne '') {
                nuget push **\DotNetForms*.nupkg -NoSymbols True -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
            }
        }
